// Menu data organized by sections

export const menu: Record<string, { item: string; price: number }[]> = {
  "Friday - Mains": [
    { item: "Small Cod (Mini)", price: 7.95 },
    { item: "Regular Cod", price: 8.95 },
    { item: "Haddock", price: 9.65 },
    { item: "Plaice", price: 9.95 },
    { item: "Scampi", price: 7.95 },
    { item: "Fish Roe", price: 2.55 },
    { item: "Fishcake", price: 2.2 },
    { item: "Small Plain Sausage", price: 1.4 },
    { item: "Small Battered Sausage", price: 1.5 },
    { item: "Jumbo Sausage", price: 2.55 },
    { item: "Jumbo Battered Sausage", price: 2.65 },
    { item: "Saveloy", price: 2.4 },
    { item: "Saveloy Battered", price: 2.5 },
    { item: "Beef Burger", price: 5.7 },
    { item: "Chicken Burger", price: 6.85 },
    { item: "SFC Chicken Burger", price: 7.45 },
    { item: "Veggie Burger", price: 5.5 },
    { item: "Cheese Burger", price: 6.0 },
    { item: "Cod Burger", price: 7.45 },
    { item: "1/2 Chicken", price: 8.95 },
    { item: "6 Chicken Nuggets", price: 5.2 },
    { item: "SFC Goujons (4)", price: 6.85 },
    { item: "Steak & Kidney Pie", price: 4.25 },
    { item: "Chicken & Mushroom Pie", price: 4.25 },
    { item: "All Steak Pie", price: 4.25 },
    { item: "Doner Kebab Pitta Fold", price: 8.65 },
    { item: "Doner Kebab Wrap", price: 8.9 },
    { item: "Doner Kebab Meat", price: 8.35 },
    { item: "Doner Kebab Meat & Chips", price: 8.95 },
    { item: "Tikka Kebab Fold", price: 9.5 },
    { item: "Mixed Kebab", price: 9.75 },
    { item: "Vegan Sausage", price: 1.95 },
    { item: "Vegan Chick N Strips 5", price: 7.95 },
    { item: "Vegan Steak & Onion Pie", price: 4.95 },
    { item: "Vegan Chicken & Mush Pie", price: 4.25 },
    { item: "Vegan Fishless Flippers", price: 7.95 },
  ],

  "Friday - Sides": [
    { item: "Small Chips", price: 3.4 },
    { item: "Large Chips", price: 4.55 },
    { item: "Small Chips with Cheese", price: 5.4 },
    { item: "Large Chips with Cheese", price: 6.85 },
    { item: "Curly Fries", price: 5.2 },
    { item: "Curly Fries with Cheese", price: 7.4 },
    { item: "Sweet Pot Fries", price: 5.2 },
    { item: "Cheesy Sweet Pot Fries", price: 7.4 },
    { item: "Small Curry Sauce", price: 1.7 },
    { item: "Large Curry Sauce", price: 2.5 },
    { item: "Small Mushy Peas", price: 1.7 },
    { item: "Large Mushy Peas", price: 2.0 },
    { item: "Small Baked Beans", price: 1.7 },
    { item: "Large Baked Beans", price: 2.0 },
    { item: "Small Gravy", price: 1.7 },
    { item: "Large Gravy", price: 2.0 },
    { item: "Large Onion Rings", price: 3.25 },
    { item: "Sm Spicy Curry Sauce", price: 1.7 },
    { item: "Lg Spicy Curry Sauce", price: 2.0 },
    { item: "Mozzarella Sticks", price: 4.95 },
    { item: "Ketchup Squeezeme", price: 0.5 },
    { item: "Tartar Sauce Squeezeme", price: 0.5 },
    { item: "Mayo Squeezeme", price: 0.5 },
    { item: "Bottle Ketchup", price: 2.5 },
    { item: "Bottle Vinegar", price: 1.95 },
    { item: "Buttered Roll", price: 0.7 },
    { item: "Pickled Egg", price: 1.0 },
    { item: "Pickled Gherkin", price: 1.0 },
    { item: "Pickled Onion", price: 1.0 },
  ],

  "Saturday - Pasties": [
    { item: "Medium Traditional Steak Cornish Pasty", price: 3 },
    { item: "Beef & Stilton Pasty", price: 3 },
    { item: "Cheese & Bacon Pasty", price: 3 },
    { item: "Cheese, Ham & Leek Pasty", price: 3 },
    { item: "Chicken & Chorizo Pasty", price: 3 },
    { item: "Creamy Chicken Pasty", price: 3 },
    { item: "Chilli Beef & Cheese Pasty", price: 3 },
    { item: "Full English Breakfast Pasty", price: 3 },
    { item: "Lamb & Mint Pasty", price: 3 },
    { item: "Pork & Apple Pasty", price: 3 },
    { item: "Spicy Chicken Pasty", price: 3 },
    { item: "Steak & Ale Pasty", price: 3 },
    { item: "Steak and Gravy Pasty", price: 3 },
    { item: "Vegan Vegetable Pasty", price: 3 },
    { item: "Vegan Wholemeal Vegetable Pasty", price: 3 },
    { item: "Vegan Spicy Vegetable Pasty", price: 3 },
    { item: "Vegan Moroccan Chickpea & Sweet Potato Pasty", price: 3 },
    { item: "Vegan Apple & Blackcurrant Pasty", price: 3 },
    { item: "Cheese & Onion Pasty (v)", price: 3 },
    { item: "Broccoli, Cheese & Sweetcorn Pasty (v)", price: 3 },
    { item: "Spinach & Ricotta Pasty (v)", price: 3 },
    { item: "Vegetable Pasty (v)", price: 3 },
    { item: "Wholemeal Vegetable Pasty (v)", price: 3 },
    { item: "Spicy Vegetable Pasty (v)", price: 3 },
    { item: "Moroccan Chickpea & Sweet Potato Pasty", price: 3 },
    { item: "Gluten Free Traditional Steak Cornish Pasty", price: 3 },
  ],
};

export type Menu = typeof menu;
